### ISSUE TITLE
Support for excluding pattern inside scss

### ISSUE THREAD

**Issue by martinpl** [cmalven/vite-plugin-sass-glob-import#14]
Hello,

I see that we can define "ignorePaths" in plugins options but that works for all files. It would be nice if we could add excluding patterns per file.

So for example we could do that: 

style.scss
```
@import "../components/**/*.scss";
@import "!../components/**/*-admin.scss";
```

admin.scss
```
@import "../components/**/*-admin.scss";
```

Thanks!

**Comment by kryp71c** [comment]
Since this project uses [glob](https://github.com/isaacs/node-glob) you should already have that option.
Glob allows you to specify a variety of patterns including ignore patterns see the [primer on the glob repo](https://github.com/isaacs/node-glob?tab=readme-ov-file#glob-primer).

For easier globbing patterns it might be best to move the namespace to the front of the file name: `admin-...scss` instead of -`...-admin.scss`
Then, in your example, you could do:

style.scss
```
// import all scss files in components except files that start with admin.
@import "../components/**/!(admin)*.scss";
```

admin.scss
```
// import all scss files in components that start with admin.
@import "../components/**/admin*.scss;
```

**Comment by cmalven** [comment]
Going to close this since the suggested approach (a second glob that cancels out the first) is pretty non-standard for globs and hopefully the approach suggested by @kryp71c will work for you.
