### ISSUE TITLE
Stylelint Vite plugins don't seem to work with vite-plugin-sass-glob-import

### ISSUE THREAD

**Issue by maximedaoust** [cmalven/vite-plugin-sass-glob-import#3]
I try my luck, since this issue is not only about this plugin.

Linting is an integral part of most dev tools today. Trying to switch to Vite's ecosystem from Webpack, the currently available plugins (like [@amatlash/vite-plugin-stylelint](https://www.npmjs.com/package/@amatlash/vite-plugin-stylelint)) don't seem to lint files imported by this plugin globbing.  

Are you using any style linting tools (like stylelint) and if so how you use it in combination with vite-plugin-sass-glob-import ?
If not, would you know the cause or possible solutions ?

Thank you in advance.

**Comment by cmalven** [comment]
@maximedaoust I typically handle stylelint and eslint linting through my editor, and also on commit using https://www.npmjs.com/package/lint-staged so I've never had a reason to configure Vite to lint my files.

But out of curiosity I added https://www.npmjs.com/package/@amatlash/vite-plugin-stylelint to a test project using `sass-glob-import` and you're right - it doesn't seem to process files that are imported with a glob.

However, this isn't just affecting files imported with a glob. Even if I import a file directly, such as `@import 'files/file-a.scss';`, `vite-plugin-stylelint` isn't finding any linting errors in that file.

Are you seeing the same thing? If so, the issue is probably with `vite-plugin-stylelint` and I would create an issue on their repo.

**Comment by maximedaoust** [comment]
@cmalven You're totally right, as soon as it's an import, it doesn't matter if it's a glob or not, it doesn't work. Sorry for the inconvenience and thanks for testing.

**Comment by cmalven** [comment]
@maximedaoust No problem!
